### ISSUE TITLE
Make the webui available at https://logistics-wizard.mybluemix.net

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard-webui#17]
As a **user of the demo**, I expect the Logistics Wizard demo user interface to be available at https://logistics-wizard.mybluemix.net

We recently moved the webui to its own module. However we still deploy the controller under the logistics-wizard and the webui under logistics-wizard-webui. Aim of this story is to deploy the controller at logistics-wizard-controller.mybluemix.net and the webui at logistics-wizard.mybluemix.net.

The webui being a different app than the controller, it will need to be able to find the controller endpoint. This can't be hardcoded as each user could deploy the app under their own name.

Also as the controller will be available under a new route (logistics-wizard-controller), it makes sense to also rename the respective GitHub project name.

**Comment by l2fprod** [comment]
No matter the changes we do, we should keep a "logistics-wizard" GitHub repo as the entry point to the demo. The current one has several Wiki pages we want to keep.

This means we should move the controller code into its own GitHub repo and keep logistics-wizard as the main repo containing documentation on the project (wiki) and a README linking together all the components of the demo (erp, recommendation, webui, controller, etc).

- logistics-wizard (mainly documentation)
 - logistics-wizard-erp -> ERP service simulator, deployed at logistics-wizard-erp.mybluemix.net
 - logistics-wizard-webui -> UI built with React, deployed at logistics-wizard.mybluemix.net
 - logistics-wizard-controller -> API for the UI, deployed at logistics-wizard-controller.mybluemix.net or logistics-wizard.mybluemix.net/api/v1 to ease the integration with the UI
 - (and later the logistics-wizard-recommendation service would follow the same path as the ERP)

**Comment by l2fprod** [comment]
@rvennam what's your thinking about renaming the logistics-wizard to logistics-wizard-controller? See my comment above https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/17#issuecomment-244066427

**Comment by rvennam** [comment]
I agree with moving the controller code to logistics-wizard-controller and keeping the logistics-wizard repo for doc/toolchain, etc

**Comment by rvennam** [comment]
Works well.
