### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard-webui#3]
@Austinauth commented on [Thu Aug 11 2016](https://github.com/IBM-Bluemix/logistics-wizard/issues/166)

Complete UX & Visual for Logistics Wizard landing page

* Content incoming from @jakepeyser 
* Basic description of the app
* Architecture diagram
* IT components & services meant for showcase
* Source code link (Global header?)
* Entry flow trigger

Reference step 1 of the [original experience diagram](https://ibm.app.box.com/notes/75279614890?view_comment=109205265)

---

@Austinauth commented on [Mon Aug 15 2016](https://github.com/IBM-Bluemix/logistics-wizard/issues/166#issuecomment-239920031)

@kingtraceyj Did you need me to mock anything up for this?

---

@kingtraceyj commented on [Mon Aug 15 2016](https://github.com/IBM-Bluemix/logistics-wizard/issues/166#issuecomment-239921384)

@Austinauth i think what ben did was a great start. i'll use that for the basis. we'll just need the content  to fully design it.

---

@kingtraceyj commented on [Mon Aug 22 2016](https://github.com/IBM-Bluemix/logistics-wizard/issues/166#issuecomment-241555273)

Attached is the comp of the landing page.

There are a few calls to action.

- github source code link at the top
- a button to try it live (is this possible or does anyone who uses it need to fork it and use it?)
- a link to the wiki -- this needs some copy edits. should we call out that it's linking to git hub? jake suggested we could call it user manual or something along those lines.

any feedback would be appreciated!

![lw_landingpage](https://cloud.githubusercontent.com/assets/20582179/17872052/eefc93a2-6883-11e6-8ffe-e321b1a2b671.png)

**Comment by kingtraceyj** [comment]
@LRRoberts0122 

here are the svgs. i need to add the computer/laptop/mobile image with updated screens but i'll get that to you today.

also, i attached a "legend" to help with the circles since they're so many and they're all different.
![map legend thing](https://cloud.githubusercontent.com/assets/20582179/18099634/1582fbd6-6ead-11e6-8628-f287cd36785f.png)


[logisticswizard_svgs.zip](https://github.com/IBM-Bluemix/logistics-wizard-webui/files/445487/logisticswizard_svgs.zip)

**Comment by LRRoberts0122** [comment]
Thanks @kingtraceyj 

I started working on it. =) 

@colbycheeze Started working on the styles for the global button thingie. It's looking pretty good. =) Still need to figure out how to pass some of the props - for example, classes, but overall, it's working pretty well? =)

![image](https://cloud.githubusercontent.com/assets/2066489/18107131/4ef66cb2-6ecc-11e6-8490-d85191712a8f.png)

**Comment by LRRoberts0122** [comment]
I've been working on a few components over Thurs and Fri. Need to finish the header, but the other components are 'done' (mostly). 

@kingtraceyj  Still needs the updated computer image thingie.
![image](https://cloud.githubusercontent.com/assets/2066489/18278932/80824a24-7419-11e6-878e-21b5ce9eea37.png)

![image](https://cloud.githubusercontent.com/assets/2066489/18278987/a36499f2-7419-11e6-864b-5dfa3d4622e9.png)

![image](https://cloud.githubusercontent.com/assets/2066489/18279003/b099ebe0-7419-11e6-9527-1a7df642436c.png)

Gonna finish the header and go over some things with Colby and finish up before making a pull request. Then, I have to hook up the routes so the root directory points here.

**Comment by LRRoberts0122** [comment]
Here's an update of the Landing Page so far! There are still a few things to be done. 

- Need to replace the header BG image.
- Need an image graphic for the Logistics Wizard section.

![image](https://cloud.githubusercontent.com/assets/2066489/18291534/d8632e0a-744d-11e6-8555-32afc20f0249.png)

![image](https://cloud.githubusercontent.com/assets/2066489/18291589/7bc5376e-744e-11e6-9371-3aef7b27f7c6.png)

![image](https://cloud.githubusercontent.com/assets/2066489/18291595/937583fa-744e-11e6-9d57-2f80ae9b9a62.png)

![image](https://cloud.githubusercontent.com/assets/2066489/18291597/9e16945c-744e-11e6-8aeb-324516b88c64.png)

![image](https://cloud.githubusercontent.com/assets/2066489/18291602/a83d9a48-744e-11e6-95f3-47dfe50a289e.png)

(There's still some refinements to be made, but it's coming along nicely, I think!)

**Comment by LRRoberts0122** [comment]
Also, the Github Icon isn't there atm. I need to update to the SVG solution that @colbycheeze has in the refactored GlobalNav. =) Just making a note.

**Comment by kingtraceyj** [comment]
@LRRoberts0122 

attached is a png for the header. i'm having issues exporting the svg with the correct opacity and i don't want to be a blocker. once we're both back in the office we can sit and figure it. in the meantime if you want to use a png this should work. i'm working on the other image! coming soon ....

![landingpage_header](https://cloud.githubusercontent.com/assets/20582179/18319271/98436f54-74ea-11e6-9f03-662964f329ec.png)

**Comment by kingtraceyj** [comment]
@LRRoberts0122  here's the last image
![lw_showcase](https://cloud.githubusercontent.com/assets/20582179/18320310/ea82c8c4-74ee-11e6-85e8-9176b9e48c2e.png)

**Comment by LRRoberts0122** [comment]
Thank you @kingtraceyj ^_^

**Comment by LRRoberts0122** [comment]
@kingtraceyj Also, if you have an AI file, I can fix it. I think the opacity issue is because of the type of blend mode the circles have? At least that's my guess. I fixed it by giving it a similar blue color, and setting the opacity in Illustrator. =)

I know you're busy, so if you just wanna toss me the file, I can fix it. ^_^
