### ISSUE TITLE
Create UI for "CreateNewUser" action in role switcher

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard-webui#47]
No longer valid with new create demo/login design (it's done automatically)

**Comment by l2fprod** [comment]
@colbycheeze 

I would go for a dialog asking "Name" (that we could prefill)
and selecting one of the available retail storage (one without a manager set):

![image](https://cloud.githubusercontent.com/assets/12746550/18442472/2671f9ec-7911-11e6-94e7-772d858d6eb6.png)

**Comment by l2fprod** [comment]
from @colbycheeze 

I think it would be easier to just have like 20-30 random names it could pull from, and instead of a dropdown…have a select list / radios…since there are only a few locations (design best practices are to stay away from dropdowns unless there is no other option) so it could just be as simple as “Choose a location” and then a list of locations, then when you click one…it creates it

**Comment by l2fprod** [comment]
https://github.com/IBM-Bluemix/logistics-wizard-webui/tree/create-retailer

**Comment by colbycheeze** [comment]
Spoke with Ram about just having all 5 retail managers created in tandem with demo session creation. There doesn't seem to be any benefit to a tech seller being able to manually them up theirselves.

Correct me if I'm wrong.

This would eliminate the need to build all of this, and instead I'd just add the api calls alongside the demo creation saga code.

**Comment by l2fprod** [comment]
@colbycheeze @rvennam 

Makes sense.

In that case, let's handle this on the ERP API side when we call POST /Demos. In the ERP code, in common/models/demo.js, Demo.newDemo creates the demo, seeds with data and creates the supply manager. We can create the retailer store managers there and assign them to the stores.

We would also remove the /Demos/{guid}/createUser method from the ERP API (and controller side too).

**Comment by colbycheeze** [comment]
That would be great. Would make the front end code a lot easier as well.
