### ISSUE TITLE
Simplify demo creation to a click of a button

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard-webui#49]
As a user, I can begin a demo session by clicking a button or entering a previous demo guid and hitting enter, and if a previous session exists I am automatically redirected, without needing to enter any additional information.

Since we don't have a "real" login feature, this can be a way for people to keep track of demo sessions they have already created, which we could pull from in the "create demo" page and just show a list of existing demos by guid.

This eliminates the need for sending emails in order to keep track of them.
The url of the demo itself could still be copy pasted to anyone, or bookmarked in order to come back to it later as well.

Can look something like this:
![](https://d17oy1vhnax1f7.cloudfront.net/items/170c0t213u250z1D3H2e/Screen%20Shot%202016-09-09%20at%2012.07.59%20PM.png?v=a10bda8a)

**Comment by colbycheeze** [comment]
Going even further with this idea...we could make it even easier but literally removing all of this...for someone coming to the demo for the first time, we can simply have a "Begin Logistics Wizard Demo" button that just creates a session (who cares what the "name" of it is anyways)

Then, store that guid in localstorage and just automatically log in returning users to the last visited dashboard (if it exists)...

Could also add an input field below the "Start Demo" where they can paste in the guid to join an existing demo (just another way of joining an existing session, even though they could just copy paste the full url into the browser)

**Comment by rvennam** [comment]
Ya, I like that better. Creating and naming a "demo" seems like an unnecessary overhead. We don't need to name it. guid is enough if they want to pick up where they left off

**Comment by colbycheeze** [comment]
Here is what it could look like:
![screen shot 2016-09-22 at 2 51 07 pm](https://cloud.githubusercontent.com/assets/8884298/18763690/0c4754de-80d4-11e6-9d34-a08efba180e2.png)

Wouldn't need to list existing sessions, since instead we would just auto-redirect to the last visited session.

**Comment by rvennam** [comment]
lgtm
