### ISSUE TITLE
Hook up actual actions / data to Global Nav

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard-webui#5]
Story #2 

This is related to controlling the demo from the meta level, switching roles etc.

 - Will be setting up the router to go to home from clicking the title
 - Role switcher will show up depending on if demo session is logged in or not
 - Role switcher items will fire off two actions, `switchRole` and `createNewManager`
 - And then we can put an external link on the github icon

Since this requires hooking up to redux, wrapping in a HoC to pass the state/actions, and firing off api calls etc it can be a chance for you to learn how that stuff works.

**Comment by LRRoberts0122** [comment]
+ Watch Redux videos to get a good understanding. We'll pair laters for learning! =)

**Comment by colbycheeze** [comment]
Update on this: I've finished the Role Switcher component to accept the role data and fire off corresponding functions from props.

Now I am finishing up refactoring the demos reducer to properly mold the api call data into the state and associate users with their store.

The data fetching action is kicked off by entering the route now, instead of the component being mounted.

I just have to finish up writing in the login piece that is fired off after the demo gets called (which is mostly just refactoring since I have most of it)

Then I can hook them up and we should be good. I think it will take another day and it should be done.
