### ISSUE TITLE
Remove the email field from the user interface

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-webui#55]
It is not yet implemented on the backend. Also removing the configuration of a SMTP server will make the overall setup easier.

Users can bookmark the page or with #49 we can keep track of the generated demo GUID in the localstorage.

Email should be removed:
- from the web ui #49 
- [x] from the toolchain configuration 
- [x] from the backend code https://github.com/IBM-Bluemix/logistics-wizard-controller/issues/6

**Comment by colbycheeze** [comment]
Will be handling this in #49

**Comment by l2fprod** [comment]
@colbycheeze we will need to cleanup the backend code + toolchain to remove all references to this email - so this #55 is not really a duplicate.

**Comment by colbycheeze** [comment]
Wouldn't you want to create an issue on the backend board for that? I just have it marked as duplicate here for web ui related task.

**Comment by l2fprod** [comment]
yes - just wanted to confirm that was the plan so not really a duplicate, rather an umbrella for the 3 impacted areas.

**Comment by l2fprod** [comment]
moving this back to inprogress to handle the changes needed in the backend to complete this enhancement.

**Comment by rvennam** [comment]
lgtm
