### ISSUE TITLE
Landing page links and diagram

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard-webui#57]
Landing page has various buttons/links that are currently not wired. 
Architecture diagram should just point to our box version so that we don't have to maintain duplicates

**Comment by colbycheeze** [comment]
Could this be a use case for trying out the Bluemix (or Softlayer) CDN for storing our image assets (or even the static front end javascript/css could be deployed to a CDN if it improves performance / loading times)

**Comment by rvennam** [comment]
Maybe, but we ready have too many components in our architecture/deployment. One of the goals was to keep this easy for tech sellers to recreate and demo.

**Comment by colbycheeze** [comment]
Okay that's fair. Was just wondering how valuable it would be to squeeze as much Bluemix tech into it that made sense so we can showcase what services we offer and how it all comes together.
